export const products = [
  {
    id: 1,
    name: "Aria Ceramic Pour-Over Set",
    category: "Home & Living",
    price: 58,
    oldPrice: 72,
    image: "/images/products/coffee.jpg",
    rating: 4.8,
    reviews: 214,
    sale: true,
  },
  {
    id: 2,
    name: "Nimbus Wireless Charger",
    category: "Tech & Gadgets",
    price: 39,
    image: "/images/products/charger.jpg",
    rating: 4.6,
    reviews: 389,
  },
  {
    id: 3,
    name: "Resistance Band Set",
    category: "Fitness",
    price: 28,
    oldPrice: 34,
    image: "/images/products/shoes.jpg",
    rating: 4.7,
    reviews: 502,
    sale: true,
  },
  {
    id: 4,
    name: "Minimalist Desk Lamp",
    category: "Home & Living",
    price: 64,
    image: "/images/products/lamp.jpg",
    rating: 4.9,
    reviews: 167,
  },
];